server:
  port: ${CONFIG_SERVER_PORT_INT}
spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
  application:
    name: ${APPLICATION_NAME}
  security:
    user:
      name: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASS}
encrypt:
  key: ${CONFIG_SERVER_ENCRYPT_KEY}        
---
name: local
environment: localhost
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          password: ${GITHUB_TOKEN}
          username: ${GITHUB_USER}
          strictHostKeyChecking: 'false'
          ignore-local-ssh-settings: 'true'
          uri: ${GITHUB_URL}
          clone-on-start: true
          default-label: ${GITHUB_BRANCH}
          search-paths: 'profiles/{application}/local'
encrypt:
  key: ${CONFIG_SERVER_ENCRYPT_KEY}
logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud:
          config: DEBUG
          git: DEBUG

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      probes:
        enabled: true
springdoc:
  api-docs:
    path: /api-docs