version: '3.0'

services:
  cos:
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_NAME}
    build:
      context: .
    networks:
      - bzn-network
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"  
    environment:
    - SPRING_ACTIVE_PROFILE=${SPRING_ACTIVE_PROFILE}
    - APPLICATION_NAME=${APPLICATION_NAME}
    - GITHUB_TOKEN=${GITHUB_TOKEN}
    - GITHUB_USER=${GITHUB_USER}
    - CONFIG_SERVER_USER=${CONFIG_SERVER_USER}
    - CONFIG_SERVER_PASS=${CONFIG_SERVER_PASS}
    - CONFIG_SERVER_ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
    - GITHUB_BRANCH=${GITHUB_BRANCH}
    - GITHUB_URL=${GITHUB_URL}
    - CONFIG_SERVER_PORT_INT=${CONFIG_SERVER_PORT_INT}
    ports:
      - "${CONFIG_SERVER_PORT_EXT}:${CONFIG_SERVER_PORT_INT}"

networks:
  bzn-network:
    external: true